import { Skeleton } from './spine-core/Skeleton';
import { SkeletonData } from './spine-core/SkeletonData';
import { AnimationState } from './spine-core/AnimationState';
import { StencilStates, BlendStates } from './core/SkeletonMaterial';
import { Script } from 'oasis-engine';
export declare class SpineRenderer extends Script {
    private static QUAD_TRIANGLES;
    private static VERTEX_SIZE;
    private vertices;
    private tempColor;
    private _skeleton;
    private _asset;
    private _state;
    private _batches;
    private _nextBatchIndex;
    private _vertexCount;
    private _stencilStates;
    private _blendStates;
    private _depthMask;
    private _priority;
    zOffset: number;
    autoUpdate: boolean;
    get asset(): SkeletonData;
    get state(): AnimationState;
    get skeleton(): Skeleton;
    get batches(): any[];
    setSkeletonData(asset: SkeletonData): void;
    setCustomStencil(states: StencilStates): void;
    setCustomBlend(states: BlendStates): void;
    setDepthMask(depthMask: boolean): void;
    setInitialRenderPriority(priority: number): void;
    disposeCurrentSkeleton(): void;
    getVertexCount(): void;
    onUpdate(delta: number): void;
    updateState(deltaTime: number): void;
    private clearBatches;
    private nextBatch;
    private updateGeometry;
}
